Update the msg-level option in idet.sh
idet.sh generates an error with recent versions of mpv.  Edited the idet.sh script to use modern syntax. 

```
$ ./mpv/TOOLS/idet.sh infile.mp4 
Error parsing commandline option msg-level: option requires parameter
Make sure you're using e.g. '--msg-level=value' instead of '--msg-level value'.
Exiting... (Fatal error)
ERROR: Less than 50% or 250 frames are determined.
```