configure: fix warnings in check programs
Mark local functions in configure tests as static; fixes the warnings:
tmp.c:1: warning: no previous prototype for 'foo'
tmp.c:2: warning: no previous prototype for 'func'
tmp.c:3: warning: no previous prototype for 'catch'

git-svn-id: svn://svn.mplayerhq.hu/mplayer/trunk@32228 b3059339-0415-0410-9bf9-f77b7e298cf2

Add some missing headers to configure checks; fixes the warnings:
tmp.c:3: warning: implicit declaration of function 'exit'
tmp.c:6: warning: implicit declaration of function 'printf'
tmp.c:4: warning: implicit declaration of function 'printf'

git-svn-id: svn://svn.mplayerhq.hu/mplayer/trunk@32229 b3059339-0415-0410-9bf9-f77b7e298cf2

Fix parameter types in swab() check; fixes the warnings:
tmp.c:3: warning: null argument where non-null required (argument 1)
tmp.c:3: warning: null argument where non-null required (argument 2)

git-svn-id: svn://svn.mplayerhq.hu/mplayer/trunk@32230 b3059339-0415-0410-9bf9-f77b7e298cf2

Remove unnecessary extern declarations from aalib check; fixes the warnings:
tmp.c:2: warning: redundant redeclaration of 'aa_defparams'
tmp.c:3: warning: redundant redeclaration of 'aa_defrenderparams'

git-svn-id: svn://svn.mplayerhq.hu/mplayer/trunk@32231 b3059339-0415-0410-9bf9-f77b7e298cf2

Remove bogus cast from configure check; fixes the warning:
tmp.c:21: warning: passing argument 2 of 'iconv' from incompatible pointer type

git-svn-id: svn://svn.mplayerhq.hu/mplayer/trunk@32233 b3059339-0415-0410-9bf9-f77b7e298cf2

Initialize variable in libspeex configure check; fixes the warning:
tmp.c:2: warning: 'dec' is used uninitialized in this function

git-svn-id: svn://svn.mplayerhq.hu/mplayer/trunk@32237 b3059339-0415-0410-9bf9-f77b7e298cf2

Initialize variable in giflib check; fixes the warning:
tmp.c:5: warning: 'gif.UserData' is used uninitialized in this function

git-svn-id: svn://svn.mplayerhq.hu/mplayer/trunk@32242 b3059339-0415-0410-9bf9-f77b7e298cf2

Cast return value to long instead of int in byte order check.
This avoids the following warning on 64 bit systems:
tmp.c:3: warning: cast from pointer to integer of different size

git-svn-id: svn://svn.mplayerhq.hu/mplayer/trunk@32250 b3059339-0415-0410-9bf9-f77b7e298cf2